#ifndef VERSION_H
#define VERSION_H

#define APP_VERSION_MAJOR 0
#define APP_VERSION_MINOR 1
#define APP_VERSION_PATCH 0

#define APP_VERSION_STRING "0.1.0"
#define APP_VERSION_STRING_WITH_NAME "CSim2 v" APP_VERSION_STRING

#endif // VERSION_H